---
title: "Introduction to R"
format: revealjs
editor: visual
Author: Kyri Janssen
---


## Project management in RStudio

-   RStudio is an integrated development environment (IDE).
-   R is integrated into RStudio.

<strong>RStudio provides a useful feature</strong>: creating a self-contained working space (i.e. working directory).

You can create projects in existing directories (folders) or create a new one.

## Creating RStudio Project

To create a project, go to:

-   `File`

-   `New Project`

-   `New directory`

-   Name your project : `data-carpentry`

-   `Create project`

## Organising working directory

-   `data/` - your raw data. **READ ONLY**
-   `data_output/` - your data output **READ AND WRITE**
-   `documents/` - the documentation associated with the project (e.g. cookbook)
-   `fig_output/` - your figure outputs **WRITE ONLY**
-   `scripts/` - your code **READ AND WRITE**

## Two main ways to interact with R

-   Test and play environment within the interactive **R console**
-   Write and save an **R script (.R file)**

|          | Console                      | R script                                   |
|----------------------|-------------------------|-------------------------|
| **Pros** | Immediate results            | Work lost once you close RStudio           |
| **Cons** | Complete record of your work | Messy if you just want to print things out |

## Vector

-   Store multiple values in one object

-   All values have to be of the same data-type

-   c(`100`, `200`, `300`)

-   c(Apples, Pears, Oranges)

-   **Note**: vector data in the geospatial context is different from vector data!

## Data types

Data type refers to a type of information that is stored by a value. It can be:

-   `numerical` (a number)

-   `integer` (a number without information about decimal points)

-   `logical` (a boolean - are values TRUE or FALSE?)

-   `character` (a text/ string of characters)

-   `complex` (a complex number)

-   `raw` (raw bytes)

## Data structures

Besides vectors you will also come across:

-   **Data frames**: two-dimensional data structure \| combination of vectors of the same length
-   **List**: can have arbitrary data structure and can mix with data types
-   **Matrices**: two-dimensional data structures containing elements of the same data type

## Excercise

Combine the abcd_vector with the numeric_vector

What is the data type of this new vector, and why?
