---
title: Guidelines for local workshop data: Metadata and instructions for using alternative datasets
output: html
---

For the Geospatial Data Carpentry for Urbanism (GDCU) workshop you can use either the provided datasets for the Netherlands or other data, for example equivalent or similar data for your own country. This document describes the provided data, including the variable names and properties, and the data sources. This can help you to find alternative data for other countries and, if needed, to adjust them to the lessons thought in this workshop. The text of the lessons mentions Dutch data, but this can also be adjusted easily.

Provided data comes mainly from the OpenStreetMap, except one dataset which comes from the Statistics Netherlands (CBS). Each part of the workshop uses a different dataset, namely:

• Part 1: Dutch municipalities

• Part 2: Municipality of Delft

• Part 3: Part of the municipality of Delft

• Part 4: Municipality of Brielle

Table 1 summarises the main properties of all the datasets from the Netherlands.

| Dataset | List of variables | Source | Size |
|---------|-------------------|--------|------|
|         |                   |        |      |
|         |                   |        |      |
|         |                   |        |      |
|         |                   |        |      |

Table 1: Summary of the provided datasets

For each of the datasets, Table 2 summarises the main properties of the variables, including the coding of missing values.

| Dataset | Variable name | Variable type | Missing values |
|---------|---------------|---------------|----------------|
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |
|         |               |               |                |

Table 2: Main properties of the variables

## Using alternative datasets for other countries

For the parts of the workshop using OpenStreetMap data, you can use data for other countries from the same source, but keep in mind that availability of the OpenStreetMap data is not the same worldwide. If a specific variable listed above is not available for your country, you can use another variable from the OpenStreetMap as long as it fits in the lesson plan. While the availability of the OpenStreetMap data is not the same worldwide, the structure of the data and variables is the same. You can therefore make use of this open data source and choose appropriate variables available locally. Or you may find the same variables as in the Dutch OpenStreetMap data, but from another source available in your country. In this case, please make sure that the types of the variables are the same and that the missing values are coded in the same way.

For Part 1, using the data from the Statistics Netherlands, you can search for alternative sources from your country, such as the national statistics office or other governmental institutions. Possibly, data from your own or your colleagues’ research can be used.

After choosing and adjusting your alternative dataset, and before running the workshop, data needs to be tested. Please follow the lesson plan to see if you can execute all the commands. Also, pay attention that the results you get fit within the programme of the lesson – that you can continue with the next steps without disruption.
